"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, FileText, Link2, Route } from "lucide-react";
import { CAREERS } from "@/lib/catalog";
import type { AppState } from "@/lib/types";

export default function Onboarding() {
  const router = useRouter();
  const [state, setState] = useState<AppState>(); const [step, setStep] = useState(1); const [paths, setPaths] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [profile, setProfile] = useState<AppState["profile"]>({ preferredName: "", university: "", program: "B.Tech", branch: "Computer Science and Engineering", cohort: "2024", semester: 1, programLength: 8, termStatus: "ongoing", weeklyHours: 3, language: "English" });
  useEffect(() => { fetch("/api/session").then((r) => r.json()).then((s: AppState) => { setState(s); setProfile(s.profile); setPaths(s.paths.map((p) => p.id)); setStep(Math.min(s.onboardingStep || 1, 4)); }); }, []);
  function set<K extends keyof AppState["profile"]>(key: K, value: AppState["profile"][K]) { setProfile((p) => ({ ...p, [key]: value })); }
  async function persist(next: number, complete = false) {
    setBusy(true); setError("");
    const response = await fetch("/api/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "onboarding", payload: { profile, paths, step: next, complete }, baseVersion: state?.version }) });
    const data = await response.json(); setBusy(false);
    if (!response.ok) return setError(data.message ?? "Could not save this step.");
    setState(data); if (complete) router.push("/app/careers"); else setStep(next);
  }
  async function upload(form: HTMLFormElement) {
    setBusy(true); setError(""); const response = await fetch("/api/documents", { method: "POST", body: new FormData(form) }); const data = await response.json(); setBusy(false);
    if (!response.ok) setError(data.message); else setState(data.state);
  }
  if (!state) return <div className="onboarding-page"><div className="onboarding-wrap skeleton"/></div>;
  return <main className="onboarding-page grid-bg"><div className="onboarding-wrap"><a className="brand" href="/"><span className="brand-mark"><Route size={18}/></span>Pathwise</a><div className="progress" aria-label={`Step ${step} of 4`}>{[1,2,3,4].map((n) => <span key={n} className={n <= step ? "done" : ""}/>)}</div><section className="form-card card">
    {step === 1 && <><span className="eyebrow">Step 1 · Academic context</span><h1>Meet your starting point</h1><p>You can join from any semester. We won’t assume earlier courses were passed.</p><div className="form-grid">
      <div className="field"><label htmlFor="name">Preferred name *</label><input id="name" className="input" value={profile.preferredName} onChange={(e) => set("preferredName", e.target.value)}/></div>
      <div className="field"><label htmlFor="university">University *</label><input id="university" className="input" placeholder="Type or enter manually" value={profile.university} onChange={(e) => set("university", e.target.value)}/></div>
      <div className="field"><label htmlFor="program">Program *</label><input id="program" className="input" value={profile.program} onChange={(e) => set("program", e.target.value)}/></div>
      <div className="field"><label htmlFor="branch">Branch *</label><input id="branch" className="input" value={profile.branch} onChange={(e) => set("branch", e.target.value)}/></div>
      <div className="field"><label htmlFor="cohort">Admission / cohort year *</label><input id="cohort" className="input" value={profile.cohort} onChange={(e) => set("cohort", e.target.value)}/></div>
      <div className="field"><label htmlFor="semester">Current semester *</label><select id="semester" className="input" value={profile.semester} onChange={(e) => set("semester", Number(e.target.value))}>{Array.from({length:profile.programLength},(_,i)=><option key={i+1}>{i+1}</option>)}</select></div>
      <div className="field"><label htmlFor="length">Program length (semesters)</label><input id="length" className="input" type="number" min="2" max="16" value={profile.programLength} onChange={(e) => set("programLength", Number(e.target.value))}/></div>
      <div className="field"><label htmlFor="term">This semester is…</label><select id="term" className="input" value={profile.termStatus} onChange={(e) => set("termStatus", e.target.value)}><option value="ongoing">Ongoing</option><option value="about_to_start">About to start</option><option value="just_completed">Just completed</option><option value="results_pending">Completed; results pending</option></select></div>
    </div></>}
    {step === 2 && <><span className="eyebrow">Step 2 · Academic evidence</span><h1>Add what you have</h1><p>A curriculum URL, text PDF, or neither—all three routes work. Uploaded presence alone does not unlock a claim.</p><form onSubmit={(e) => { e.preventDefault(); upload(e.currentTarget); }} className="stack"><input type="hidden" name="type" value="curriculum"/><div className="field"><label htmlFor="url"><Link2 size={14}/> Official curriculum or department URL</label><input id="url" name="url" className="input" type="url" placeholder="https://university.edu/program/curriculum"/></div><div className="dropzone"><label htmlFor="file"><FileText size={18}/> Or upload a text-based curriculum PDF</label><input id="file" name="file" className="input" type="file" accept="application/pdf" style={{marginTop:10}}/><p className="fine">PDF only · 10 MB max · image-only scans require OCR, which is not configured.</p></div><button className="btn" disabled={busy} type="submit">{busy ? "Reading…" : "Process source"}</button></form>{state.documents.length > 0 && <div className="doc-list" style={{marginTop:16}}>{state.documents.map((d)=><div className="doc" key={d.id}><span><strong>{d.name}</strong><br/><span className="fine">{d.message}</span></span><span className={`badge ${d.status === "ready" ? "success" : "warn"}`}>{d.status}</span></div>)}</div>}<div className="notice" style={{marginTop:16}}>You may continue with general guidance. Course eligibility will remain provisional until applicable rules and records are known.</div></>}
    {step === 3 && <><span className="eyebrow">Step 3 · Academic position</span><h1>{profile.semester === 1 ? "Your first-term plan" : profile.semester === profile.programLength ? "Your final-term picture" : `What is known before semester ${profile.semester}?`}</h1><p>{profile.semester === 1 ? "No past marksheet is required. Add your current or upcoming plan later in My Semester." : "A cumulative transcript is enough. You do not need a separate file for every term, and missing results stay unknown."}</p>{profile.semester > 1 && <form onSubmit={(e) => { e.preventDefault(); upload(e.currentTarget); }} className="dropzone"><input type="hidden" name="type" value="transcript"/><label htmlFor="transcript"><FileText size={18}/> Optional cumulative transcript or marksheet</label><input id="transcript" name="file" className="input" type="file" accept="application/pdf" style={{marginTop:10}}/><button className="btn" disabled={busy} style={{marginTop:10}}>Process private document</button><p className="fine">Use synthetic records only in this prototype.</p></form>}<div className="form-grid"><div className="field"><label htmlFor="hours">Weekly exploration time</label><select id="hours" className="input" value={profile.weeklyHours} onChange={(e) => set("weeklyHours", Number(e.target.value))}><option value="1">About 1 hour</option><option value="3">2–3 hours</option><option value="5">4–6 hours</option><option value="8">7+ hours</option></select></div><div className="field"><label htmlFor="language">Learning language</label><input id="language" className="input" value={profile.language} onChange={(e) => set("language", e.target.value)}/></div></div></>}
    {step === 4 && <><span className="eyebrow">Step 4 · Paths to explore</span><h1>Keep more than one future open</h1><p>Select any number, including none. These are your choices—not an AI prediction.</p><div className="chips" role="group" aria-label="Career paths">{CAREERS.map((career) => { const active=paths.includes(career.id); return <button type="button" aria-pressed={active} className={`chip ${active ? "active" : ""}`} key={career.id} onClick={()=>setPaths((old)=>active?old.filter((x)=>x!==career.id):[...old,career.id])}>{active && <Check size={14}/>} {career.label}</button>; })}</div><div className="notice"><strong>Ready to review:</strong> {profile.program}, {profile.branch} · semester {profile.semester} · {paths.length ? `${paths.length} paths selected` : "still exploring"}.<br/><span className="fine">Missing academic evidence will stay visible in each affected recommendation.</span></div></>}
    {error && <p className="notice" role="alert" style={{color:"var(--error)",marginTop:16}}>{error}</p>}<div className="step-actions"><button className="btn" disabled={step===1||busy} onClick={()=>setStep((s)=>s-1)}><ArrowLeft size={16}/> Back</button><button className="btn btn-primary" disabled={busy || (step===1 && (!profile.preferredName || !profile.university))} onClick={()=>persist(step===4?4:step+1,step===4)}>{busy ? "Saving…" : step===4 ? "Open Career Planner" : "Save & continue"}<ArrowRight size={16}/></button></div>
  </section></div></main>;
}
